### ISSUE TITLE
vim url 404

### ISSUE THREAD

**Issue by pencilcheck** [choppsv1/homebrew-term24#4]
==> Installing vim from choppsv1/homebrew-term24
==> Downloading http://ftp.debian.org/debian/pool/main/v/vim/vim_7.4.430.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "vim"
Download failed: http://ftp.debian.org/debian/pool/main/v/vim/vim_7.4.430.orig.tar.gz

**Comment by yachi** [comment]
The color patch is only available in head:

```
brew install --HEAD choppsv1/term24/vim
```

**Comment by pencilcheck** [comment]
Cool I see the changes. Thx
