### ISSUE TITLE
tmux 2.0 update issue

### ISSUE THREAD

**Issue by bangedorrunt** [choppsv1/homebrew-term24#5]
Hi,

Upgrading tmux 2.0 from homebrew broke your `24bit true color` patch.  

Please fix it, thanks so much!

**Comment by choppsv1** [comment]
I've removed the unnecessary hunk that was causing the patch to fail. I
haven't upgraded to 2.0 yet though so give it a try and let me know if
all is well.

Thanks,
Chris.

Thanh Dũng TRƯƠNG writes:

**Comment by bangedorrunt** [comment]
Hi @choppsv1,

I've tried to reinstall `tmux 2.0` and your patch was still defective. Here is what I did

``` bash
brew uninstall --force tmux
brew install choppsv1/term24/tmux
brew upgrade tmux
```

This is screenshot I took after upgrading to `tmux 2.0`

![screenshot](https://cloud.githubusercontent.com/assets/1514823/7559541/c6610d3c-f7fb-11e4-8484-e096ee274aea.png)

If I use `brew reinstall choppsv1/term24/tmux --HEAD`, I got this error:

￼![screenshot](https://cloud.githubusercontent.com/assets/1514823/7559575/2a8473bc-f7fc-11e4-9871-fa690a5d225f.png)

**Comment by choppsv1** [comment]
Forgot to commit/push the change, please try again. Don’t forget to 
update the tap before building.

Thanks,
Chris.

**Comment by bangedorrunt** [comment]
Many thanks @choppsv1, I just updated `tap` and it works perfectly with `tmux 2.0` now :+1:
