### ISSUE TITLE
Emacs colors with tmux 2.1

### ISSUE THREAD

**Issue by gsarwate** [choppsv1/homebrew-term24#8]
tmux in Homebrew is now updated to 2.1. When I updated the tmux to Homebrew version, I lost all colors in the Emacs (tapped from this repo) in tmux mode. If I fallback to tmux 2.0 from this repo, the colors work fine.

**Comment by choppsv1** [comment]
I've updated the tap to work with tmux 2.1 now.

**Comment by gsarwate** [comment]
I just got the update using brew by tapping this repo. Thanks a lot!
